name: Deployment pipeline

on:
  push:
    branches:
    - github-actions 

jobs:
  deply:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - name: Install dependencies 
        run: npm install
      - name: App start
        run: npm start & npx wait-on http://localhost:3000
      - name: Integration tests
        run: npm run test-cypress